# -*- coding: utf-8 -*-
"""Copy of E-Commerce Customer & Revenue Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eyFLPdxRuPiImYfnvs2ACc94vAzMmPKj

#  E-Commerce Customer & Revenue Analysis  

###  Project Overview  
This project analyzes an e-commerce dataset to evaluate revenue trends, customer behaviour, geographic performance and customer segmentation using RFM analysis.  

The goal is to extract actionable business insights to improve customer retention, revenue growth and strategic decision-making.

---

###  Business Objectives
- Analyze overall revenue performance
- Identify top-performing states and product categories
- Evaluate repeat purchase behavior
- Segment customers using RFM analysis
- Provide data-driven business recommendations

---

###  Tools Used
- Python
- Pandas
- Matplotlib
- Customer Segmentation (RFM Framework)

---

###  Key Metrics Analys Key Metrics Analyzed
- Total Revenue
- Total Orders
- Average Order Value (AOV)
- Repeat Customer Rate
- Revenue by State
- Revenue by Product Category
- RFM Segmentation
"""

import pandas as pd

customers = pd.read_csv("olist_customers_dataset.csv")
orders = pd.read_csv("olist_orders_dataset.csv")
payments = pd.read_csv("olist_order_payments_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")

customers.head()

# Commented out IPython magic to ensure Python compatibility.
# %who

orders = orders[orders["order_status"] == "delivered"]

orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"]
)

payments_grouped = (
    payments.groupby("order_id")["payment_value"]
    .sum()
    .reset_index()
)

merged1 = orders.merge(customers, on="customer_id", how="left")

merged2 = merged1.merge(payments_grouped, on="order_id", how="left")

merged3 = merged2.merge(order_items, on="order_id", how="left")

master = merged3.merge(products, on="product_id", how="left")

master.head()
master.shape

master.to_csv("master_transactions_clean.csv", index=False)

master.isnull().sum()

master["product_category_name"].fillna("Unknown", inplace=True)

master = master.dropna(subset=["payment_value"])

# Fill missing product category
master["product_category_name"] = master["product_category_name"].fillna("Unknown")

# Drop rows with missing payment_value
master = master.dropna(subset=["payment_value"])

# Drop unnecessary delivery + dimension columns
master = master.drop(columns=[
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
    "shipping_limit_date",
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
])

master.isnull().sum()

master.shape

order_level = master.groupby(
    ["order_id", "customer_unique_id", "order_purchase_timestamp",
     "customer_state"]
).agg({
    "payment_value": "first",   # total payment already grouped
    "price": "sum",
    "freight_value": "sum"
}).reset_index()

order_level.shape
order_level.head()

order_level.shape

print(globals())

df = order_level

df['order_month'] = df['order_purchase_timestamp'].dt.to_period('M')

total_revenue = df['payment_value'].sum()
print("Total Revenue:", total_revenue)

total_orders = df['order_id'].nunique()
print("Total Orders:", total_orders)

total_customers = df['customer_unique_id'].nunique()
print("Total Customers:", total_customers)

aov = total_revenue / total_orders
print("Average Order Value:", round(aov,2))

"""Repeat Orders = 96,477 - 93,357 = 3,120"""

repeat_customers = df.groupby('customer_unique_id')['order_id'].nunique()
repeat_rate = (repeat_customers > 1).sum() / df['customer_unique_id'].nunique()

print("Repeat Customer Rate:", round(repeat_rate*100,2), "%")

monthly_revenue = df.groupby('order_month')['payment_value'].sum()

monthly_revenue.plot(figsize=(12,5), title="Monthly Revenue Trend")

state_revenue = df.groupby('customer_state')['payment_value'].sum().sort_values(ascending=False)

state_revenue.head(10)

5770266.19 / 15422461.77

category_revenue = df.groupby('product_category_name')['payment_value'].sum().sort_values(ascending=False)

category_revenue.head(10)

master.columns

category_revenue = master.groupby('product_category_name')['payment_value'].sum().sort_values(ascending=False)

category_revenue.head(10)

top_customers = master.groupby('customer_unique_id')['payment_value'].sum().sort_values(ascending=False)

top_customers.head(10)

import datetime as dt

snapshot_date = df['order_purchase_timestamp'].max() + dt.timedelta(days=1)

rfm = df.groupby('customer_unique_id').agg({
    'order_purchase_timestamp': lambda x: (snapshot_date - x.max()).days,
    'order_id': 'nunique',
    'payment_value': 'sum'
})

rfm.rename(columns={
    'order_purchase_timestamp': 'Recency',
    'order_id': 'Frequency',
    'payment_value': 'Monetary'
}, inplace=True)

rfm.head()

rfm['R_score'] = pd.qcut(rfm['Recency'], 4, labels=[4,3,2,1])
rfm['F_score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 4, labels=[1,2,3,4])
rfm['M_score'] = pd.qcut(rfm['Monetary'], 4, labels=[1,2,3,4])

rfm['RFM_Score'] = rfm['R_score'].astype(str) + rfm['F_score'].astype(str) + rfm['M_score'].astype(str)

rfm.head()

rfm['RFM_Score'].value_counts().head(10)

import matplotlib.pyplot as plt

monthly_revenue = df.groupby('order_month')['payment_value'].sum()

plt.figure(figsize=(10,5))
plt.plot(monthly_revenue.index.astype(str), monthly_revenue.values)
plt.title("Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""Insight: Revenue shows a consistent upward trend, indicating business growth driven primarily by new customer acquisition."""

state_revenue = df.groupby('customer_state')['payment_value'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(8,5))
plt.bar(state_revenue.index, state_revenue.values)
plt.title("Top 10 States by Revenue")
plt.xlabel("State")
plt.ylabel("Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""Insight: Revenue is highly concentrated in SP (~37%), creating geographic dependency risk."""

category_revenue = master.groupby('product_category_name')['payment_value'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,5))
plt.bar(category_revenue.index, category_revenue.values)
plt.title("Top 10 Product Categories by Revenue")
plt.xlabel("Category")
plt.ylabel("Revenue")
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

"""Insight: Home & lifestyle and beauty categories dominate revenue, indicating strong consumer demand in essential and discretionary segments."""

rfm['Segment'] = 'Others'

rfm.loc[(rfm['R_score']=='4') & (rfm['F_score']=='4'), 'Segment'] = 'Champions'
rfm.loc[(rfm['F_score']=='4'), 'Segment'] = 'Loyal Customers'
rfm.loc[(rfm['R_score']=='1'), 'Segment'] = 'At Risk'
rfm.loc[(rfm['R_score']=='1') & (rfm['F_score']=='1'), 'Segment'] = 'Hibernating'

segment_counts = rfm['Segment'].value_counts()

plt.figure(figsize=(8,5))
plt.bar(segment_counts.index, segment_counts.values)
plt.title("Customer Segmentation (RFM)")
plt.xlabel("Segment")
plt.ylabel("Number of Customers")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""Insight: Majority customers fall into low-frequency segments, indicating weak retention and high dependency on acquisition.

Business Recommendations :

Improve retention through loyalty programs
Upsell in high-performing categories
Expand marketing in RJ & MG
Develop subscription model for beauty segment
"""